# Generated by Django 3.0.8 on 2020-07-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='catag',
            field=models.CharField(default='action', max_length=50),
            preserve_default=False,
        ),
    ]
